import type { PublicProviderProfile } from "./api/types";

export const mockProviderProfile: PublicProviderProfile = {
  id: 1,
  name: "شركة البناء الحديث",
  photo: { id: 1, url: "" },
  providerType: "Resource",
  licenseNumber: "BS-2021-0458",
  phone: "+963 944 123 456",
  email: "contact@modernbuild.sy",
  bio: "مقاولات عامة وأعمال إنشائية متكاملة بخبرة تتجاوز 15 عاماً في تنفيذ المشاريع السكنية والتجارية بأعلى معايير الجودة.",
  workSitesCount: 12,
  inventoryCount: 340,
  fulfillmentRate: 96,
  totalInvoiced: 1284500,
  rating: 4.7,
  reviewsCount: 128,
  workSites: [
    {
      id: 1,
      name: "برج الرازي السكني",
      logo: { id: 1, url: "" },
      workSiteType: "سكني",
      address: "شارع المزة، دمشق",
      location: "33.5138,36.2765",
      status: "active",
    },
    {
      id: 2,
      name: "مجمع القصر التجاري",
      logo: { id: 2, url: "" },
      workSiteType: "تجاري",
      address: "شارع بغداد، حلب",
      location: "36.2021,37.1343",
      status: "active",
    },
    {
      id: 3,
      name: "فيلات الياسمين",
      logo: { id: 3, url: "" },
      workSiteType: "سكني",
      address: "منطقة الياسمين، حمص",
      location: "34.7315,36.7228",
      status: "on-hold",
    },
  ],
  inventory: [
    {
      id: 1,
      name: "إسمنت بورتلاندي",
      imageURL: "",
      description: "إسمنت عالي الجودة للمنشآت الخرسانية.",
      category: { id: 1, name: "مواد البناء", categoryType: "Resource" },
      price: 8.5,
      isAvailable: true,
      unit: "Bag",
    },
    {
      id: 2,
      name: "حديد تسليح 16مم",
      imageURL: "",
      description: "قضبان حديد تسليح مطابقة للمواصفات.",
      category: { id: 1, name: "مواد البناء", categoryType: "Resource" },
      price: 720,
      isAvailable: true,
      unit: "Ton",
    },
    {
      id: 3,
      name: "طوب أحمر",
      imageURL: "",
      description: "طوب بناء أحمر فاخر.",
      category: { id: 2, name: "مواد البياض", categoryType: "Resource" },
      price: 0.35,
      isAvailable: false,
      unit: "Piece",
    },
    {
      id: 4,
      name: "رمل مغسول",
      imageURL: "",
      description: "رمل بناء مغسول ناعم.",
      category: { id: 1, name: "مواد البناء", categoryType: "Resource" },
      price: 42,
      isAvailable: true,
      unit: "SquareMeter",
    },
  ],
  reviews: [
    {
      id: 1,
      authorName: "أحمد الحسن",
      rating: 5,
      comment: "التزام ممتاز بالمواعيد وجودة عمل عالية جداً.",
      createdAt: "2024-11-12",
    },
    {
      id: 2,
      authorName: "سارة خالد",
      rating: 4,
      comment: "فريق محترف وتعامل راقٍ، أنصح بالتعامل معهم.",
      createdAt: "2024-10-03",
    },
    {
      id: 3,
      authorName: "محمود عيد",
      rating: 5,
      comment: "أسعار منافسة وجودة فائقة في التنفيذ.",
      createdAt: "2024-09-21",
    },
  ],
};
