import type { LandDetail } from "../api/types";

export const mockLandDetail: LandDetail = {
  landId: 1,
  name: "Northgate Development Land",
  isValidated: true,
  zoningType: "Residential",
  accessability: true,
  area: 24500,
  address: "123 Main St, Abu Dhabi, UAE",
  longitude: 54.3705,
  latitude: 24.4539,
  location: { longitude: 54.3705, latitude: 24.4539 },
  coverImageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80",
  border: [
    { longitude: 54.3685, latitude: 24.4525 },
    { longitude: 54.3725, latitude: 24.4525 },
    { longitude: 54.3725, latitude: 24.4553 },
    { longitude: 54.3685, latitude: 24.4553 },
  ],
  attachments: [
    { id: 1, name: "land-survey.pdf", url: "#", description: "Land Survey Report 2024" },
    { id: 2, name: "ownership-cert.pdf", url: "#", description: "Ownership Certificate" },
    { id: 3, name: "zoning-plan.pdf", url: "#", description: "Zoning Plan" },
  ],
  buildings: [
    {
      landId: 1,
      buildingId: 101,
      name: "Al-Baraka Residential Tower",
      city: "Abu Dhabi",
      streetName: "King Fahd Road",
      zoneType: "Residential",
      readinessLevel: "Operational",
      orientation: "North",
      buildingType: "Residential",
      area: 3200,
      address: "125 King Fahd Road, Abu Dhabi",
      location: { longitude: 54.3710, latitude: 24.4542 },
      coverImageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
      updateAt: "2025-01-15T10:00:00Z",
      buildingParts: [
        { id: 1, area: 800, buildingPartType: "Floor" },
        { id: 2, area: 800, buildingPartType: "Floor" },
        { id: 3, area: 800, buildingPartType: "Floor" },
        { id: 4, area: 800, buildingPartType: "Floor" },
      ],
      attachments: [
        { id: 1, name: "floor-plan.pdf", url: "#", description: "Floor Plan" },
      ],
    },
    {
      landId: 1,
      buildingId: 102,
      name: "Green Valley Mall",
      city: "Abu Dhabi",
      streetName: "Al Salam Street",
      zoneType: "Commercial",
      readinessLevel: "Under Construction",
      orientation: "South",
      buildingType: "Commercial",
      area: 5600,
      address: "Al Salam Street, Abu Dhabi",
      location: { longitude: 54.3698, latitude: 24.4535 },
      coverImageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
      updateAt: "2025-03-20T14:30:00Z",
      buildingParts: [
        { id: 1, area: 2800, buildingPartType: "Unit" },
        { id: 2, area: 2800, buildingPartType: "Unit" },
      ],
      attachments: [
        { id: 2, name: "progress-report.pdf", url: "#", description: "Construction Progress Report" },
        { id: 3, name: "permit.pdf", url: "#", description: "Building Permit" },
      ],
    },
    {
      landId: 1,
      buildingId: 103,
      name: "Tech Hub Office Complex",
      city: "Abu Dhabi",
      streetName: "Corniche Road",
      zoneType: "Office",
      readinessLevel: "Operational",
      orientation: "East",
      buildingType: "Administrative",
      area: 1800,
      address: "Corniche Road, Abu Dhabi",
      location: { longitude: 54.3718, latitude: 24.4548 },
      coverImageUrl: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=600&q=80",
      updateAt: "2024-11-08T09:15:00Z",
      buildingParts: [
        { id: 1, area: 600, buildingPartType: "Section" },
        { id: 2, area: 600, buildingPartType: "Section" },
        { id: 3, area: 600, buildingPartType: "Section" },
      ],
      attachments: [],
    },
  ],
};
