import type {
  CashFlowPoint,
  CategoryShareItem,
  ProjectTransaction,
} from "./api/types";

export const MOCK_SAMPLE_TRANSACTIONS: ProjectTransaction[] = [
  {
    id: "sample-prov-1",
    date: "2026-07-18",
    counterParty: "Concrete & Ready-Mix Co.",
    category: "provider-resource",
    direction: "expense",
    amount: 92000,
    status: "paid",
    source: "sample",
  },
  {
    id: "sample-prov-2",
    date: "2026-07-04",
    counterParty: "Steel Supply Trading",
    category: "provider-resource",
    direction: "expense",
    amount: 148000,
    status: "paid",
    source: "sample",
  },
  {
    id: "sample-prov-3",
    date: "2026-06-21",
    counterParty: "Al-Sham Electrical Works",
    category: "provider-service",
    direction: "expense",
    amount: 64000,
    status: "paid",
    source: "sample",
  },
  {
    id: "sample-prov-4",
    date: "2026-06-09",
    counterParty: "Plumbing & Sanitary Solutions",
    category: "provider-service",
    direction: "expense",
    amount: 11500,
    status: "pending",
    source: "sample",
  },
  {
    id: "sample-eng-1",
    date: "2026-07-01",
    counterParty: "Eng. Khaled Al-Hakim",
    category: "engineer",
    direction: "expense",
    amount: 45000,
    status: "paid",
    source: "sample",
  },
  {
    id: "sample-eng-2",
    date: "2026-06-15",
    counterParty: "Eng. Rana Qassem",
    category: "engineer",
    direction: "expense",
    amount: 32000,
    status: "pending",
    source: "sample",
  },
  {
    id: "sample-eng-3",
    date: "2026-05-30",
    counterParty: "Eng. Omar Zaidan",
    category: "engineer",
    direction: "expense",
    amount: 27500,
    status: "paid",
    source: "sample",
  },
  {
    id: "sample-inc-1",
    date: "2026-06-28",
    counterParty: "Investor Transfer",
    category: "other",
    direction: "income",
    amount: 400000,
    status: "paid",
    source: "sample",
  },
  {
    id: "sample-inc-2",
    date: "2026-07-25",
    counterParty: "Investor Transfer",
    category: "other",
    direction: "income",
    amount: 200000,
    status: "pending",
    source: "sample",
  },
  {
    id: "sample-oth-1",
    date: "2026-06-05",
    counterParty: "Permits & Licenses",
    category: "other",
    direction: "expense",
    amount: 8300,
    status: "paid",
    source: "sample",
  },
  {
    id: "sample-oth-2",
    date: "2026-07-12",
    counterParty: "Safety Equipment",
    category: "other",
    direction: "expense",
    amount: 5600,
    status: "overdue",
    source: "sample",
  },
];

export const MOCK_CASH_FLOW: CashFlowPoint[] = [
  { month: 0, income: 0.22, expense: 0.18 },
  { month: 1, income: 0.3, expense: 0.24 },
  { month: 2, income: 0.28, expense: 0.31 },
  { month: 3, income: 0.42, expense: 0.35 },
  { month: 4, income: 0.38, expense: 0.44 },
  { month: 5, income: 0.55, expense: 0.48 },
  { month: 6, income: 0.6, expense: 0.66 },
  { month: 7, income: 0.52, expense: 0.58 },
  { month: 8, income: 0.7, expense: 0.62 },
  { month: 9, income: 0.78, expense: 0.74 },
  { month: 10, income: 0.84, expense: 0.9 },
  { month: 11, income: 1, expense: 0.82 },
];

export const MOCK_CATEGORY_SHARES: CategoryShareItem[] = [
  { category: "workshop", value: 0.46 },
  { category: "provider-resource", value: 0.22 },
  { category: "provider-service", value: 0.16 },
  { category: "engineer", value: 0.11 },
  { category: "other", value: 0.05 },
];